spring:
  application:
    name: ai-code-assistant
  profiles:
    active: local


langchain4j:
  community:
    dashscope:
      chat-model:
        #model-name: qwen3.5-plus
        model-name: qwen3.5-plus-2026-02-15
        # 需要在application-local.yml配置api-key
        #api-key: <your api key>
      embedding-model:
        #model-name: tongyi-embedding-vision-plus-2026-03-06
        model-name: text-embedding-v4
        #base-url: https://dashscope.aliyuncs.com/api/v1/services/embeddings/multimodal-embedding/multimodal-embedding
